// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Sync.proto

package com.stone.proto;

public final class Syncs {
  private Syncs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SyncOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Sync)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 syncTime = 1;</code>
     */
    boolean hasSyncTime();
    /**
     * <code>required int64 syncTime = 1;</code>
     */
    long getSyncTime();

    /**
     * <code>repeated .Human humans = 2;</code>
     */
    java.util.List<com.stone.proto.Humans.Human> 
        getHumansList();
    /**
     * <code>repeated .Human humans = 2;</code>
     */
    com.stone.proto.Humans.Human getHumans(int index);
    /**
     * <code>repeated .Human humans = 2;</code>
     */
    int getHumansCount();
    /**
     * <code>repeated .Human humans = 2;</code>
     */
    java.util.List<? extends com.stone.proto.Humans.HumanOrBuilder> 
        getHumansOrBuilderList();
    /**
     * <code>repeated .Human humans = 2;</code>
     */
    com.stone.proto.Humans.HumanOrBuilder getHumansOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Sync}
   *
   * <pre>
   * sync
   * </pre>
   */
  public static final class Sync extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Sync)
      SyncOrBuilder {
    // Use Sync.newBuilder() to construct.
    private Sync(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Sync(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Sync defaultInstance;
    public static Sync getDefaultInstance() {
      return defaultInstance;
    }

    public Sync getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Sync(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              syncTime_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                humans_ = new java.util.ArrayList<com.stone.proto.Humans.Human>();
                mutable_bitField0_ |= 0x00000002;
              }
              humans_.add(input.readMessage(com.stone.proto.Humans.Human.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          humans_ = java.util.Collections.unmodifiableList(humans_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stone.proto.Syncs.internal_static_Sync_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stone.proto.Syncs.internal_static_Sync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stone.proto.Syncs.Sync.class, com.stone.proto.Syncs.Sync.Builder.class);
    }

    public static com.google.protobuf.Parser<Sync> PARSER =
        new com.google.protobuf.AbstractParser<Sync>() {
      public Sync parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Sync(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Sync> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SYNCTIME_FIELD_NUMBER = 1;
    private long syncTime_;
    /**
     * <code>required int64 syncTime = 1;</code>
     */
    public boolean hasSyncTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 syncTime = 1;</code>
     */
    public long getSyncTime() {
      return syncTime_;
    }

    public static final int HUMANS_FIELD_NUMBER = 2;
    private java.util.List<com.stone.proto.Humans.Human> humans_;
    /**
     * <code>repeated .Human humans = 2;</code>
     */
    public java.util.List<com.stone.proto.Humans.Human> getHumansList() {
      return humans_;
    }
    /**
     * <code>repeated .Human humans = 2;</code>
     */
    public java.util.List<? extends com.stone.proto.Humans.HumanOrBuilder> 
        getHumansOrBuilderList() {
      return humans_;
    }
    /**
     * <code>repeated .Human humans = 2;</code>
     */
    public int getHumansCount() {
      return humans_.size();
    }
    /**
     * <code>repeated .Human humans = 2;</code>
     */
    public com.stone.proto.Humans.Human getHumans(int index) {
      return humans_.get(index);
    }
    /**
     * <code>repeated .Human humans = 2;</code>
     */
    public com.stone.proto.Humans.HumanOrBuilder getHumansOrBuilder(
        int index) {
      return humans_.get(index);
    }

    private void initFields() {
      syncTime_ = 0L;
      humans_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSyncTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getHumansCount(); i++) {
        if (!getHumans(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, syncTime_);
      }
      for (int i = 0; i < humans_.size(); i++) {
        output.writeMessage(2, humans_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, syncTime_);
      }
      for (int i = 0; i < humans_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, humans_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.stone.proto.Syncs.Sync parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.Syncs.Sync parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.Syncs.Sync parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.Syncs.Sync parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.Syncs.Sync parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.Syncs.Sync parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.stone.proto.Syncs.Sync parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.stone.proto.Syncs.Sync parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.stone.proto.Syncs.Sync parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.Syncs.Sync parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.stone.proto.Syncs.Sync prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Sync}
     *
     * <pre>
     * sync
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Sync)
        com.stone.proto.Syncs.SyncOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stone.proto.Syncs.internal_static_Sync_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stone.proto.Syncs.internal_static_Sync_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stone.proto.Syncs.Sync.class, com.stone.proto.Syncs.Sync.Builder.class);
      }

      // Construct using com.stone.proto.Syncs.Sync.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHumansFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        syncTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (humansBuilder_ == null) {
          humans_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          humansBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stone.proto.Syncs.internal_static_Sync_descriptor;
      }

      public com.stone.proto.Syncs.Sync getDefaultInstanceForType() {
        return com.stone.proto.Syncs.Sync.getDefaultInstance();
      }

      public com.stone.proto.Syncs.Sync build() {
        com.stone.proto.Syncs.Sync result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stone.proto.Syncs.Sync buildPartial() {
        com.stone.proto.Syncs.Sync result = new com.stone.proto.Syncs.Sync(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.syncTime_ = syncTime_;
        if (humansBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            humans_ = java.util.Collections.unmodifiableList(humans_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.humans_ = humans_;
        } else {
          result.humans_ = humansBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stone.proto.Syncs.Sync) {
          return mergeFrom((com.stone.proto.Syncs.Sync)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stone.proto.Syncs.Sync other) {
        if (other == com.stone.proto.Syncs.Sync.getDefaultInstance()) return this;
        if (other.hasSyncTime()) {
          setSyncTime(other.getSyncTime());
        }
        if (humansBuilder_ == null) {
          if (!other.humans_.isEmpty()) {
            if (humans_.isEmpty()) {
              humans_ = other.humans_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureHumansIsMutable();
              humans_.addAll(other.humans_);
            }
            onChanged();
          }
        } else {
          if (!other.humans_.isEmpty()) {
            if (humansBuilder_.isEmpty()) {
              humansBuilder_.dispose();
              humansBuilder_ = null;
              humans_ = other.humans_;
              bitField0_ = (bitField0_ & ~0x00000002);
              humansBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHumansFieldBuilder() : null;
            } else {
              humansBuilder_.addAllMessages(other.humans_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSyncTime()) {
          
          return false;
        }
        for (int i = 0; i < getHumansCount(); i++) {
          if (!getHumans(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stone.proto.Syncs.Sync parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stone.proto.Syncs.Sync) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long syncTime_ ;
      /**
       * <code>required int64 syncTime = 1;</code>
       */
      public boolean hasSyncTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 syncTime = 1;</code>
       */
      public long getSyncTime() {
        return syncTime_;
      }
      /**
       * <code>required int64 syncTime = 1;</code>
       */
      public Builder setSyncTime(long value) {
        bitField0_ |= 0x00000001;
        syncTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 syncTime = 1;</code>
       */
      public Builder clearSyncTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        syncTime_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.stone.proto.Humans.Human> humans_ =
        java.util.Collections.emptyList();
      private void ensureHumansIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          humans_ = new java.util.ArrayList<com.stone.proto.Humans.Human>(humans_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.stone.proto.Humans.Human, com.stone.proto.Humans.Human.Builder, com.stone.proto.Humans.HumanOrBuilder> humansBuilder_;

      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public java.util.List<com.stone.proto.Humans.Human> getHumansList() {
        if (humansBuilder_ == null) {
          return java.util.Collections.unmodifiableList(humans_);
        } else {
          return humansBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public int getHumansCount() {
        if (humansBuilder_ == null) {
          return humans_.size();
        } else {
          return humansBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public com.stone.proto.Humans.Human getHumans(int index) {
        if (humansBuilder_ == null) {
          return humans_.get(index);
        } else {
          return humansBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public Builder setHumans(
          int index, com.stone.proto.Humans.Human value) {
        if (humansBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHumansIsMutable();
          humans_.set(index, value);
          onChanged();
        } else {
          humansBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public Builder setHumans(
          int index, com.stone.proto.Humans.Human.Builder builderForValue) {
        if (humansBuilder_ == null) {
          ensureHumansIsMutable();
          humans_.set(index, builderForValue.build());
          onChanged();
        } else {
          humansBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public Builder addHumans(com.stone.proto.Humans.Human value) {
        if (humansBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHumansIsMutable();
          humans_.add(value);
          onChanged();
        } else {
          humansBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public Builder addHumans(
          int index, com.stone.proto.Humans.Human value) {
        if (humansBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHumansIsMutable();
          humans_.add(index, value);
          onChanged();
        } else {
          humansBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public Builder addHumans(
          com.stone.proto.Humans.Human.Builder builderForValue) {
        if (humansBuilder_ == null) {
          ensureHumansIsMutable();
          humans_.add(builderForValue.build());
          onChanged();
        } else {
          humansBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public Builder addHumans(
          int index, com.stone.proto.Humans.Human.Builder builderForValue) {
        if (humansBuilder_ == null) {
          ensureHumansIsMutable();
          humans_.add(index, builderForValue.build());
          onChanged();
        } else {
          humansBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public Builder addAllHumans(
          java.lang.Iterable<? extends com.stone.proto.Humans.Human> values) {
        if (humansBuilder_ == null) {
          ensureHumansIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, humans_);
          onChanged();
        } else {
          humansBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public Builder clearHumans() {
        if (humansBuilder_ == null) {
          humans_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          humansBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public Builder removeHumans(int index) {
        if (humansBuilder_ == null) {
          ensureHumansIsMutable();
          humans_.remove(index);
          onChanged();
        } else {
          humansBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public com.stone.proto.Humans.Human.Builder getHumansBuilder(
          int index) {
        return getHumansFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public com.stone.proto.Humans.HumanOrBuilder getHumansOrBuilder(
          int index) {
        if (humansBuilder_ == null) {
          return humans_.get(index);  } else {
          return humansBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public java.util.List<? extends com.stone.proto.Humans.HumanOrBuilder> 
           getHumansOrBuilderList() {
        if (humansBuilder_ != null) {
          return humansBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(humans_);
        }
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public com.stone.proto.Humans.Human.Builder addHumansBuilder() {
        return getHumansFieldBuilder().addBuilder(
            com.stone.proto.Humans.Human.getDefaultInstance());
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public com.stone.proto.Humans.Human.Builder addHumansBuilder(
          int index) {
        return getHumansFieldBuilder().addBuilder(
            index, com.stone.proto.Humans.Human.getDefaultInstance());
      }
      /**
       * <code>repeated .Human humans = 2;</code>
       */
      public java.util.List<com.stone.proto.Humans.Human.Builder> 
           getHumansBuilderList() {
        return getHumansFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.stone.proto.Humans.Human, com.stone.proto.Humans.Human.Builder, com.stone.proto.Humans.HumanOrBuilder> 
          getHumansFieldBuilder() {
        if (humansBuilder_ == null) {
          humansBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.stone.proto.Humans.Human, com.stone.proto.Humans.Human.Builder, com.stone.proto.Humans.HumanOrBuilder>(
                  humans_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          humans_ = null;
        }
        return humansBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Sync)
    }

    static {
      defaultInstance = new Sync(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Sync)
  }

  public interface MoveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Move)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required .SceneObjectType objectType = 2;</code>
     */
    boolean hasObjectType();
    /**
     * <code>required .SceneObjectType objectType = 2;</code>
     */
    com.stone.proto.Humans.SceneObjectType getObjectType();

    /**
     * <code>required int32 x = 3;</code>
     */
    boolean hasX();
    /**
     * <code>required int32 x = 3;</code>
     */
    int getX();

    /**
     * <code>required int32 y = 4;</code>
     */
    boolean hasY();
    /**
     * <code>required int32 y = 4;</code>
     */
    int getY();

    /**
     * <code>required int32 sceneId = 5;</code>
     */
    boolean hasSceneId();
    /**
     * <code>required int32 sceneId = 5;</code>
     */
    int getSceneId();
  }
  /**
   * Protobuf type {@code Move}
   *
   * <pre>
   * move
   * </pre>
   */
  public static final class Move extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Move)
      MoveOrBuilder {
    // Use Move.newBuilder() to construct.
    private Move(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Move(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Move defaultInstance;
    public static Move getDefaultInstance() {
      return defaultInstance;
    }

    public Move getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Move(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.stone.proto.Humans.SceneObjectType value = com.stone.proto.Humans.SceneObjectType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                objectType_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              x_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              y_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sceneId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stone.proto.Syncs.internal_static_Move_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stone.proto.Syncs.internal_static_Move_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stone.proto.Syncs.Move.class, com.stone.proto.Syncs.Move.Builder.class);
    }

    public static com.google.protobuf.Parser<Move> PARSER =
        new com.google.protobuf.AbstractParser<Move>() {
      public Move parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Move(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Move> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int OBJECTTYPE_FIELD_NUMBER = 2;
    private com.stone.proto.Humans.SceneObjectType objectType_;
    /**
     * <code>required .SceneObjectType objectType = 2;</code>
     */
    public boolean hasObjectType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .SceneObjectType objectType = 2;</code>
     */
    public com.stone.proto.Humans.SceneObjectType getObjectType() {
      return objectType_;
    }

    public static final int X_FIELD_NUMBER = 3;
    private int x_;
    /**
     * <code>required int32 x = 3;</code>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 x = 3;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 4;
    private int y_;
    /**
     * <code>required int32 y = 4;</code>
     */
    public boolean hasY() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 y = 4;</code>
     */
    public int getY() {
      return y_;
    }

    public static final int SCENEID_FIELD_NUMBER = 5;
    private int sceneId_;
    /**
     * <code>required int32 sceneId = 5;</code>
     */
    public boolean hasSceneId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 sceneId = 5;</code>
     */
    public int getSceneId() {
      return sceneId_;
    }

    private void initFields() {
      id_ = 0L;
      objectType_ = com.stone.proto.Humans.SceneObjectType.MONSTER;
      x_ = 0;
      y_ = 0;
      sceneId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasObjectType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSceneId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, objectType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, y_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, sceneId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, objectType_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, x_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, y_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, sceneId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.stone.proto.Syncs.Move parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.Syncs.Move parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.Syncs.Move parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stone.proto.Syncs.Move parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stone.proto.Syncs.Move parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.Syncs.Move parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.stone.proto.Syncs.Move parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.stone.proto.Syncs.Move parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.stone.proto.Syncs.Move parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.stone.proto.Syncs.Move parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.stone.proto.Syncs.Move prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Move}
     *
     * <pre>
     * move
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Move)
        com.stone.proto.Syncs.MoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stone.proto.Syncs.internal_static_Move_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stone.proto.Syncs.internal_static_Move_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stone.proto.Syncs.Move.class, com.stone.proto.Syncs.Move.Builder.class);
      }

      // Construct using com.stone.proto.Syncs.Move.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        objectType_ = com.stone.proto.Humans.SceneObjectType.MONSTER;
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        sceneId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stone.proto.Syncs.internal_static_Move_descriptor;
      }

      public com.stone.proto.Syncs.Move getDefaultInstanceForType() {
        return com.stone.proto.Syncs.Move.getDefaultInstance();
      }

      public com.stone.proto.Syncs.Move build() {
        com.stone.proto.Syncs.Move result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.stone.proto.Syncs.Move buildPartial() {
        com.stone.proto.Syncs.Move result = new com.stone.proto.Syncs.Move(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.objectType_ = objectType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.y_ = y_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sceneId_ = sceneId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stone.proto.Syncs.Move) {
          return mergeFrom((com.stone.proto.Syncs.Move)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stone.proto.Syncs.Move other) {
        if (other == com.stone.proto.Syncs.Move.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasObjectType()) {
          setObjectType(other.getObjectType());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        if (other.hasSceneId()) {
          setSceneId(other.getSceneId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasObjectType()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        if (!hasSceneId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stone.proto.Syncs.Move parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stone.proto.Syncs.Move) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private com.stone.proto.Humans.SceneObjectType objectType_ = com.stone.proto.Humans.SceneObjectType.MONSTER;
      /**
       * <code>required .SceneObjectType objectType = 2;</code>
       */
      public boolean hasObjectType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .SceneObjectType objectType = 2;</code>
       */
      public com.stone.proto.Humans.SceneObjectType getObjectType() {
        return objectType_;
      }
      /**
       * <code>required .SceneObjectType objectType = 2;</code>
       */
      public Builder setObjectType(com.stone.proto.Humans.SceneObjectType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        objectType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .SceneObjectType objectType = 2;</code>
       */
      public Builder clearObjectType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        objectType_ = com.stone.proto.Humans.SceneObjectType.MONSTER;
        onChanged();
        return this;
      }

      private int x_ ;
      /**
       * <code>required int32 x = 3;</code>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 x = 3;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 x = 3;</code>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00000004;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 x = 3;</code>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000004);
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>required int32 y = 4;</code>
       */
      public boolean hasY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 y = 4;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>required int32 y = 4;</code>
       */
      public Builder setY(int value) {
        bitField0_ |= 0x00000008;
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 y = 4;</code>
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000008);
        y_ = 0;
        onChanged();
        return this;
      }

      private int sceneId_ ;
      /**
       * <code>required int32 sceneId = 5;</code>
       */
      public boolean hasSceneId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 sceneId = 5;</code>
       */
      public int getSceneId() {
        return sceneId_;
      }
      /**
       * <code>required int32 sceneId = 5;</code>
       */
      public Builder setSceneId(int value) {
        bitField0_ |= 0x00000010;
        sceneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 sceneId = 5;</code>
       */
      public Builder clearSceneId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sceneId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Move)
    }

    static {
      defaultInstance = new Move(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Move)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Sync_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Sync_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Move_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Move_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nSync.proto\032\013Human.proto\"0\n\004Sync\022\020\n\010syn" +
      "cTime\030\001 \002(\003\022\026\n\006humans\030\002 \003(\0132\006.Human\"_\n\004M" +
      "ove\022\n\n\002id\030\001 \002(\003\022$\n\nobjectType\030\002 \002(\0162\020.Sc" +
      "eneObjectType\022\t\n\001x\030\003 \002(\005\022\t\n\001y\030\004 \002(\005\022\017\n\007s" +
      "ceneId\030\005 \002(\005B\030\n\017com.stone.protoB\005Syncs"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stone.proto.Humans.getDescriptor(),
        }, assigner);
    internal_static_Sync_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Sync_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Sync_descriptor,
        new java.lang.String[] { "SyncTime", "Humans", });
    internal_static_Move_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Move_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Move_descriptor,
        new java.lang.String[] { "Id", "ObjectType", "X", "Y", "SceneId", });
    com.stone.proto.Humans.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
