// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.i4joy.akka.kok.io.protocol;

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface msgInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes data = 1;
    boolean hasData();
    com.google.protobuf.ByteString getData();
    
    // optional string PacketId = 2;
    boolean hasPacketId();
    String getPacketId();
    
    // optional int32 packetLen = 3;
    boolean hasPacketLen();
    int getPacketLen();
    
    // optional string uuid = 4;
    boolean hasUuid();
    String getUuid();
  }
  public static final class msgInfo extends
      com.google.protobuf.GeneratedMessage
      implements msgInfoOrBuilder {
    // Use msgInfo.newBuilder() to construct.
    private msgInfo(Builder builder) {
      super(builder);
    }
    private msgInfo(boolean noInit) {}
    
    private static final msgInfo defaultInstance;
    public static msgInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public msgInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.i4joy.akka.kok.io.protocol.Packet.internal_static_kok_test_client_msgInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.i4joy.akka.kok.io.protocol.Packet.internal_static_kok_test_client_msgInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bytes data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_;
    public boolean hasData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    
    // optional string PacketId = 2;
    public static final int PACKETID_FIELD_NUMBER = 2;
    private java.lang.Object packetId_;
    public boolean hasPacketId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPacketId() {
      java.lang.Object ref = packetId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          packetId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPacketIdBytes() {
      java.lang.Object ref = packetId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        packetId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 packetLen = 3;
    public static final int PACKETLEN_FIELD_NUMBER = 3;
    private int packetLen_;
    public boolean hasPacketLen() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getPacketLen() {
      return packetLen_;
    }
    
    // optional string uuid = 4;
    public static final int UUID_FIELD_NUMBER = 4;
    private java.lang.Object uuid_;
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          uuid_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      data_ = com.google.protobuf.ByteString.EMPTY;
      packetId_ = "";
      packetLen_ = 0;
      uuid_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPacketIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, packetLen_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getUuidBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPacketIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, packetLen_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getUuidBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.i4joy.akka.kok.io.protocol.Packet.msgInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.i4joy.akka.kok.io.protocol.Packet.msgInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.i4joy.akka.kok.io.protocol.Packet.msgInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.i4joy.akka.kok.io.protocol.Packet.msgInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.i4joy.akka.kok.io.protocol.Packet.msgInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.i4joy.akka.kok.io.protocol.Packet.msgInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.i4joy.akka.kok.io.protocol.Packet.msgInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.i4joy.akka.kok.io.protocol.Packet.msgInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.i4joy.akka.kok.io.protocol.Packet.msgInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.i4joy.akka.kok.io.protocol.Packet.msgInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.i4joy.akka.kok.io.protocol.Packet.msgInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.i4joy.akka.kok.io.protocol.Packet.msgInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.i4joy.akka.kok.io.protocol.Packet.internal_static_kok_test_client_msgInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.i4joy.akka.kok.io.protocol.Packet.internal_static_kok_test_client_msgInfo_fieldAccessorTable;
      }
      
      // Construct using com.i4joy.akka.kok.io.protocol.Packet.msgInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        packetId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        packetLen_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.i4joy.akka.kok.io.protocol.Packet.msgInfo.getDescriptor();
      }
      
      public com.i4joy.akka.kok.io.protocol.Packet.msgInfo getDefaultInstanceForType() {
        return com.i4joy.akka.kok.io.protocol.Packet.msgInfo.getDefaultInstance();
      }
      
      public com.i4joy.akka.kok.io.protocol.Packet.msgInfo build() {
        com.i4joy.akka.kok.io.protocol.Packet.msgInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.i4joy.akka.kok.io.protocol.Packet.msgInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.i4joy.akka.kok.io.protocol.Packet.msgInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.i4joy.akka.kok.io.protocol.Packet.msgInfo buildPartial() {
        com.i4joy.akka.kok.io.protocol.Packet.msgInfo result = new com.i4joy.akka.kok.io.protocol.Packet.msgInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.packetId_ = packetId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.packetLen_ = packetLen_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.uuid_ = uuid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.i4joy.akka.kok.io.protocol.Packet.msgInfo) {
          return mergeFrom((com.i4joy.akka.kok.io.protocol.Packet.msgInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.i4joy.akka.kok.io.protocol.Packet.msgInfo other) {
        if (other == com.i4joy.akka.kok.io.protocol.Packet.msgInfo.getDefaultInstance()) return this;
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasPacketId()) {
          setPacketId(other.getPacketId());
        }
        if (other.hasPacketLen()) {
          setPacketLen(other.getPacketLen());
        }
        if (other.hasUuid()) {
          setUuid(other.getUuid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              data_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              packetId_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              packetLen_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              uuid_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes data = 1;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        data_ = value;
        onChanged();
        return this;
      }
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      
      // optional string PacketId = 2;
      private java.lang.Object packetId_ = "";
      public boolean hasPacketId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPacketId() {
        java.lang.Object ref = packetId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          packetId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPacketId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        packetId_ = value;
        onChanged();
        return this;
      }
      public Builder clearPacketId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        packetId_ = getDefaultInstance().getPacketId();
        onChanged();
        return this;
      }
      void setPacketId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        packetId_ = value;
        onChanged();
      }
      
      // optional int32 packetLen = 3;
      private int packetLen_ ;
      public boolean hasPacketLen() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getPacketLen() {
        return packetLen_;
      }
      public Builder setPacketLen(int value) {
        bitField0_ |= 0x00000004;
        packetLen_ = value;
        onChanged();
        return this;
      }
      public Builder clearPacketLen() {
        bitField0_ = (bitField0_ & ~0x00000004);
        packetLen_ = 0;
        onChanged();
        return this;
      }
      
      // optional string uuid = 4;
      private java.lang.Object uuid_ = "";
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUuid(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        uuid_ = value;
        onChanged();
        return this;
      }
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      void setUuid(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        uuid_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:kok.test.client.msgInfo)
    }
    
    static {
      defaultInstance = new msgInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:kok.test.client.msgInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_kok_test_client_msgInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kok_test_client_msgInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\017kok.test.client\"J\n\007msgInfo\022" +
      "\014\n\004data\030\001 \001(\014\022\020\n\010PacketId\030\002 \001(\t\022\021\n\tpacke" +
      "tLen\030\003 \001(\005\022\014\n\004uuid\030\004 \001(\tB(\n\036com.i4joy.ak" +
      "ka.kok.io.protocolB\006Packet"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_kok_test_client_msgInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_kok_test_client_msgInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_kok_test_client_msgInfo_descriptor,
              new java.lang.String[] { "Data", "PacketId", "PacketLen", "Uuid", },
              com.i4joy.akka.kok.io.protocol.Packet.msgInfo.class,
              com.i4joy.akka.kok.io.protocol.Packet.msgInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
