// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

package com.i4joy.akka.kok.protocol;

public final class PProtocolPacket {
  private PProtocolPacket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface msgInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes writeData = 1;
    boolean hasWriteData();
    com.google.protobuf.ByteString getWriteData();
  }
  public static final class msgInfo extends
      com.google.protobuf.GeneratedMessage
      implements msgInfoOrBuilder {
    // Use msgInfo.newBuilder() to construct.
    private msgInfo(Builder builder) {
      super(builder);
    }
    private msgInfo(boolean noInit) {}
    
    private static final msgInfo defaultInstance;
    public static msgInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public msgInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.i4joy.akka.kok.protocol.PProtocolPacket.internal_static_kok_test_client_msgInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.i4joy.akka.kok.protocol.PProtocolPacket.internal_static_kok_test_client_msgInfo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bytes writeData = 1;
    public static final int WRITEDATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString writeData_;
    public boolean hasWriteData() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getWriteData() {
      return writeData_;
    }
    
    private void initFields() {
      writeData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, writeData_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, writeData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.i4joy.akka.kok.protocol.PProtocolPacket.internal_static_kok_test_client_msgInfo_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.i4joy.akka.kok.protocol.PProtocolPacket.internal_static_kok_test_client_msgInfo_fieldAccessorTable;
      }
      
      // Construct using com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        writeData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo.getDescriptor();
      }
      
      public com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo getDefaultInstanceForType() {
        return com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo.getDefaultInstance();
      }
      
      public com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo build() {
        com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo buildPartial() {
        com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo result = new com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.writeData_ = writeData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo) {
          return mergeFrom((com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo other) {
        if (other == com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo.getDefaultInstance()) return this;
        if (other.hasWriteData()) {
          setWriteData(other.getWriteData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              writeData_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes writeData = 1;
      private com.google.protobuf.ByteString writeData_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasWriteData() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getWriteData() {
        return writeData_;
      }
      public Builder setWriteData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        writeData_ = value;
        onChanged();
        return this;
      }
      public Builder clearWriteData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        writeData_ = getDefaultInstance().getWriteData();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:kok.test.client.msgInfo)
    }
    
    static {
      defaultInstance = new msgInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:kok.test.client.msgInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_kok_test_client_msgInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_kok_test_client_msgInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tmsg.proto\022\017kok.test.client\"\034\n\007msgInfo\022" +
      "\021\n\twriteData\030\001 \001(\014B.\n\033com.i4joy.akka.kok" +
      ".protocolB\017PProtocolPacket"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_kok_test_client_msgInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_kok_test_client_msgInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_kok_test_client_msgInfo_descriptor,
              new java.lang.String[] { "WriteData", },
              com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo.class,
              com.i4joy.akka.kok.protocol.PProtocolPacket.msgInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
